### ISSUE TITLE
Sector display problem of faults

### ISSUE THREAD

**Issue by cloudxin** [filecoin-project/venus-sealer#131]
When viewing the faults sector, Venus sealer cannot view how many days remain in the life cycle. This should be a countdown from 42 days.

eg:
**venus-sealer proving faults**
```
Sealer: f0xxxxx
deadline  partition  sectors
0         0          2
```

Change into
```
Sealer: f0xxxxx
deadline  partition  sectors   Expiration time
0         0          2         41.28055555555556  day
```

**Comment by diwufeiwen** [comment]
https://github.com/filecoin-project/venus-sealer/pull/133
