### ISSUE TITLE
run ./venus-sealer stop error

### ISSUE THREAD

**Issue by diwufeiwen** [filecoin-project/venus-sealer#69]
Describe the Bug

kabat@kabat1:/venus$ ~/venus-sealer/venus-sealer stop
2021-07-22T12:03:52.846+0200 ERROR api api/client.go:149 unknown repo type, are you sure you want to use GetAPI?
ERROR: could not get API info: could not get api endpoint: API not running (no endpoint)
6:06

**Comment by simlecode** [comment]
fixed: https://github.com/filecoin-project/venus-sealer/pull/74
