### ISSUE TITLE
venus-gateway exit unexpectedly

### ISSUE THREAD

**Issue by DTanniks** [filecoin-project/venus-sealer#84]
When venus-wallet stepped in to share services, venus-gateway dropped out unexpectedly。
1.`nohup ./venus-gateway --listen=/ip4/0.0.0.0/tcp/45132 run --auth-url=http://127.0.0.1:8989 > gateway.log 2>&1 &`
The venus-gateway process is normal.Then running after I configured [APIRegisterHub].
2.`nohup ./venus-wallet run > wallet.log 2>&1`
venus-gateway exit unexpectedly.
3.tail -f gateway.log
```
panic: unaligned 64-bit atomic operation

goroutine 94 [running]:
runtime/internal/atomic.panicUnaligned()
    /usr/local/go/src/runtime/internal/atomic/unaligned.go:8 +0x2d
runtime/internal/atomic.Xadd64(0xa0e64f4, 0x1, 0x0, 0x0, 0x7b)
    /usr/local/go/src/runtime/internal/atomic/asm_386.s:107 +0x11
github.com/filecoin-project/go-jsonrpc.(*wsConn).handleChanOut(0xa0e6480, 0x8cfe4e0, 0xa0d699c, 0x92, 0x1, 0x0, 0xa128a00, 0x19)
    /home/gpo/go/pkg/mod/github.com/ipfs-force-community/go-jsonrpc@v0.1.4-0.20210731021807-68e5207079bc/websocket.go:257 +0x6f
github.com/filecoin-project/go-jsonrpc.(*RPCServer).handle(0xa330960, 0x912918c, 0xa0d6918, 0xa040f20, 0x3, 0xa040f28, 0xa128a00, 0x19, 0xa4f2420, 0x1, ...)
    /home/gpo/go/pkg/mod/github.com/ipfs-force-community/go-jsonrpc@v0.1.4-0.20210731021807-68e5207079bc/handler.go:371 +0x1066
created by github.com/filecoin-project/go-jsonrpc.(*wsConn).handleCall
    /home/gpo/go/pkg/mod/github.com/ipfs-force-community/go-jsonrpc@v0.1.4-0.20210731021807-68e5207079bc/websocket.go:424 +0x1b6
```
I'm in nerpa.Thinks.

--------------------------------------------------------------
provide "goroutine 0" log

**Comment by diwufeiwen** [comment]
The version of the gateway？ We recommend using the incubation branch。

**Comment by simlecode** [comment]
Your system is 32 bits？

**Comment by DTanniks** [comment]
> Your system is 32 bits？

No，it’s 64，I'm on the master branch.

**Comment by simlecode** [comment]
> The venus-gateway process is normal.Then running after I configured [APIRegisterHub]

Please provide  `configured [APIRegisterHub]`

**Comment by simlecode** [comment]
go version ?

**Comment by DTanniks** [comment]
> go version ?

go version go1.16.4 linux/386

**Comment by simlecode** [comment]
> ```
> panic: unaligned 64-bit atomic operation
> 
> goroutine 94 [running]:
> runtime/internal/atomic.panicUnaligned()
>     /usr/local/go/src/runtime/internal/atomic/unaligned.go:8 +0x2d
> runtime/internal/atomic.Xadd64(0xa0e64f4, 0x1, 0x0, 0x0, 0x7b)
>     /usr/local/go/src/runtime/internal/atomic/asm_386.s:107 +0x11
> github.com/filecoin-project/go-jsonrpc.(*wsConn).handleChanOut(0xa0e6480, 0x8cfe4e0, 0xa0d699c, 0x92, 0x1, 0x0, 0xa128a00, 0x19)
>     /home/gpo/go/pkg/mod/github.com/ipfs-force-community/go-jsonrpc@v0.1.4-0.20210731021807-68e5207079bc/websocket.go:257 +0x6f
> github.com/filecoin-project/go-jsonrpc.(*RPCServer).handle(0xa330960, 0x912918c, 0xa0d6918, 0xa040f20, 0x3, 0xa040f28, 0xa128a00, 0x19, 0xa4f2420, 0x1, ...)
>     /home/gpo/go/pkg/mod/github.com/ipfs-force-community/go-jsonrpc@v0.1.4-0.20210731021807-68e5207079bc/handler.go:371 +0x1066
> created by github.com/filecoin-project/go-jsonrpc.(*wsConn).handleCall
>     /home/gpo/go/pkg/mod/github.com/ipfs-force-community/go-jsonrpc@v0.1.4-0.20210731021807-68e5207079bc/websocket.go:424 +0x1b6
> ```

Please provide log before `panic: unaligned 64-bit atomic operation`

**Comment by DTanniks** [comment]
> > ```
> > panic: unaligned 64-bit atomic operation
> > 
> > goroutine 94 [running]:
> > runtime/internal/atomic.panicUnaligned()
> >     /usr/local/go/src/runtime/internal/atomic/unaligned.go:8 +0x2d
> > runtime/internal/atomic.Xadd64(0xa0e64f4, 0x1, 0x0, 0x0, 0x7b)
> >     /usr/local/go/src/runtime/internal/atomic/asm_386.s:107 +0x11
> > github.com/filecoin-project/go-jsonrpc.(*wsConn).handleChanOut(0xa0e6480, 0x8cfe4e0, 0xa0d699c, 0x92, 0x1, 0x0, 0xa128a00, 0x19)
> >     /home/gpo/go/pkg/mod/github.com/ipfs-force-community/go-jsonrpc@v0.1.4-0.20210731021807-68e5207079bc/websocket.go:257 +0x6f
> > github.com/filecoin-project/go-jsonrpc.(*RPCServer).handle(0xa330960, 0x912918c, 0xa0d6918, 0xa040f20, 0x3, 0xa040f28, 0xa128a00, 0x19, 0xa4f2420, 0x1, ...)
> >     /home/gpo/go/pkg/mod/github.com/ipfs-force-community/go-jsonrpc@v0.1.4-0.20210731021807-68e5207079bc/handler.go:371 +0x1066
> > created by github.com/filecoin-project/go-jsonrpc.(*wsConn).handleCall
> >     /home/gpo/go/pkg/mod/github.com/ipfs-force-community/go-jsonrpc@v0.1.4-0.20210731021807-68e5207079bc/websocket.go:424 +0x1b6
> > ```
> 
> Please provide log before `panic: unaligned 64-bit atomic operation`

No more, that's all

**Comment by simlecode** [comment]
I found a comment at `go/src/sync/atomic/doc.go`: `BUG(rsc): On 386, the 64-bit functions use instructions unavailable before the Pentium MMX`
I'm not sure if that's the reason

go issue: https://github.com/golang/go/issues/36606

**Comment by diwufeiwen** [comment]
uname -a

**Comment by DTanniks** [comment]
> uname -a

Linux yc-12-112 4.15.0-140-generic #144-Ubuntu SMP Fri Mar 19 14:12:35 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by diwufeiwen** [comment]
> > uname -a
> 
> Linux yc-12-112 4.15.0-140-generic #144-Ubuntu SMP Fri Mar 19 14:12:35 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
> 
> Is that all the logs?

Is the program compiled on this machine

**Comment by DTanniks** [comment]
> > > uname -a
> > 
> > 
> > Linux yc-12-112 4.15.0-140-generic #144-Ubuntu SMP Fri Mar 19 14:12:35 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
> > Is that all the logs?
> 
> Is the program compiled on this machine

I don't know what happened, I didn't get this error on the other server. But when I initialized venus-sealer the log told me:
Worker: 11; Base: 403190; Target: 403190 (diff: 0)
State: complete; Current Epoch: 403190; Todo: 0

```
Done!
2021-08-05T16:06:12.030+0800	INFO	main	venus-sealer/init.go:207	Checking if repo exists
2021-08-05T16:06:12.030+0800	INFO	main	venus-sealer/init.go:220	Checking full node version
2021-08-05T16:06:12.031+0800	WARN	cliutil	apiinfo/apiinfo.go:75	API Token not set and requested, capabilities might be limited.
ERROR: websocket: bad handshake
```
this is my cil：
```
./venus-sealer init \
--actor t01000  \
--network nerpa \
--node-url /ip4/127.0.0.1/tcp/3453 \
--messager-url /ip4/127.0.0.1/tcp/39812 \
--gateway-url /ip4/127.0.0.1/tcp/45132 \
--auth-token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoibWluZXIxIiwicGVybSI6ImFkbWluIiwiZXh0IjoiIn0.XegAOGgjVYsxdlHHf0L3XHEATlX3rvYFVknMT1Rz7AA \
--no-local-storage > sealer.log 2>&1 &
```

**Comment by DTanniks** [comment]
I updated to the master branch and resolved the Venus-sealer init. When I run
`nohup./ Venus-sealer run >> sealer.log 2>&1`
I got：
```
ERROR: creating node: starting node: miner preflight checks failed: key for worker not found in local wallet

2021-08-05T17:42:44.481+0800	ERROR	storageminer	storage/wdpost_run.go:472	getting partitions: handler: websocket connection closed
2021-08-05T17:42:44.481+0800	ERROR	storageminer	storage/wdpost_run.go:107	runPoStCycle failed: failed to get chain randomness from beacon for window post (ts=403383; deadline={403383 400978 40 403378 403438 403358 403308 48 2880 60 20 70}):
    github.com/filecoin-project/venus-sealer/storage.(*WindowPoStScheduler).runPoStCycle
        /root/venus/venus-sealer/storage/wdpost_run.go:537
  - handler: websocket connection closed
```
My steps are wrong？ @diwufeiwen

**Comment by diwufeiwen** [comment]
.venus_wallet/config.toml 
[APIRegisterHub]
  RegisterAPI = ["/ip4/127.0.0.1/tcp/45132"]
  Token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoidGVzdCIsInBlcm0iOiJ3cml0ZSIsImV4dCI6IiJ9.aWoYo5MHxINSWqqV72Xzc7l1ZBc8UXkiMPIwn1NO2Fc"
  SupportAccounts = ["test"]

---------------------------------------------------------------------------------
 ./venus-auth user list
number: 1
name: test
miner: f01000
sourceType: 0   // miner:1
state 0         // 0: disable, 1: enable
comment: 
createTime: Thu, 05 Aug 2021 14:10:24 CST
updateTime: Thu, 05 Aug 2021 14:10:24 CST

 ./venus-auth token list
num     name            perm            createTime              token
1       test            write   2021-08-05 14:10:33     eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoidGVzdCIsInBlcm0iOiJ3cml0ZSIsImV4dCI6IiJ9.aWoYo5MHxINSWqqV72Xzc7l1ZBc8UXkiMPIwn1NO2Fc

**Comment by diwufeiwen** [comment]
If you just want to know how to access shared components, we have a service here for you to test, you only need to deploy venus-sealer and venus-worekr， https://venus.filecoin.io/guide/Using-venus-Shared-Modules.html， Welcome to the slack channel to communicate：https://app.slack.com/client/TEHTVS1L6/CEHHJNJS3/thread/CEHHJNJS3-1628146473.055200 @DTanniks

**Comment by DTanniks** [comment]
.venus_wallet/config.toml
```
[APIRegisterHub]
  RegisterAPI = ["/ip4/127.0.0.1/tcp/45132"]
  Token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoibWluZXIxIiwicGVybSI6ImFkbWluIiwiZXh0IjoiIn0.XegAOGgjVYsxdlHHf0L3XHEATlX3rvYFVknMT1Rz7AA"
  SupportAccounts = ["miner1"]
```
./venus-auth user list
```
number: 1
name: miner1
miner: f01000
sourceType: 0 	// miner:1
state 0 	// 0: disable, 1: enable
comment: 
createTime: Thu, 05 Aug 2021 14:09:43 CST
updateTime: Thu, 05 Aug 2021 14:09:43 CST
```
./venus-auth token list
```
1	messager	admin	2021-08-05 13:42:32	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoibWVzc2FnZXIiLCJwZXJtIjoiYWRtaW4iLCJleHQiOiIifQ.no_nHXhLCgUd9LJf7kxVBdTHBIEbcp5nEfqCWsMQN_A
2	miner		admin	2021-08-05 13:42:35	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoibWluZXIiLCJwZXJtIjoiYWRtaW4iLCJleHQiOiIifQ.jOm790V5_axIPfz4EbVGuHeiPFhFdiBAquZXjdXbUbE
3	miner1		admin	2021-08-05 13:42:37	eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoibWluZXIxIiwicGVybSI6ImFkbWluIiwiZXh0IjoiIn0.XegAOGgjVYsxdlHHf0L3XHEATlX3rvYFVknMT1Rz7AA
```
I think my configuration is ok.
@diwufeiwen

**Comment by simlecode** [comment]
show `./venus-gateway wallet list`

**Comment by DTanniks** [comment]
> show `./venus-gateway wallet list`

[
 	{
 		"Account": "miner1",
 		"SupportAccounts": [
 			"miner1"
 		],
 		"ConnectStates": [
 			{
 				"Addrs": [
 					"t3uk4jewz7uwpgv5g4qj6xmkt4uaangnjt6gaawo2ao7lonjg4k47ublpuzl4cwdwrhyvyojwumpyzf6mggc5q",
 					"t3s626pxg53xz6rv43dkuuv5xckbbxump3272vyvd6bcub2ybd5tmdlu3cwlyttqm64n62ifq7jumyrekwhopa"
 				],
 				"ChannelId": "abf374c6-87ba-434f-8a64-0a9ddc5b7b5e",
 				"Ip": "127.0.0.1:55296",
 				"RequestCount": 0,
 				"CreateTime": "2021-08-05T14:06:28.1327066+08:00"
 			}
 		]
 	}
 ]

**Comment by diwufeiwen** [comment]
Do you build your own private network or connect to the nerpa network？

**Comment by DTanniks** [comment]
> Do you build your own private network or connect to the nerpa network？

yes，I'm connected to the nerpa network，follow：[](https://venus.filecoin.io/zh/guide/Using-venus-Shared-Modules.html#%E5%AE%89%E8%A3%85venus-sealer)

**Comment by diwufeiwen** [comment]
如果您还没有miner-id，请运行以下命令来初始化sealer。请确保<OWNER_ADDRESS>中有足够资金支付gasfee，否则init将失败。

$ nohup ./venus-sealer init \
--worker <WORKER_ADDRESS> \
--owner <OWNER_ADDRESS>  \
# Choose between 32G or 64G for mainnet
--sector-size 512M \
# Choose from nerpa, calibration for testnets
# Leave out this flag for mainnet
--network nerpa \
# Config for different shared venus modules
--node-url /ip4/<IP_ADDRESS_OF_VENUS>/tcp/3453 \
--messager-url /ip4/<IP_ADDRESS_OF_VENUS_MESSAGER>/tcp/<PORT_OF_VENUS_MESSAGER> \
--gateway-url /ip4/<IP_ADDRESS_OF_VENUS_GATEWAY>/tcp/<PORT_OF_VENUS_GATEWAY> \
--auth-token <AUTH_TOKEN_FOR_ACCOUNT_NAME> \
# Flags sealer to not storing any sealed sectors on the machine it runs on
# You can leave out this flag if you are on testnet
--no-local-storage \
> sealer.log 2>&1 &

**Comment by diwufeiwen** [comment]
如果您还没有miner-id，请运行以下命令来初始化sealer。请确保<OWNER_ADDRESS>中有足够资金支付gasfee，否则init将失败

**Comment by DTanniks** [comment]
` ./venus-auth user add --name <ACCOUNT_NAME> --miner <MINER_ID>`
Is this the command to create the miner ID?

**Comment by diwufeiwen** [comment]
And your two wallets have no money in the nerpa network and cannot create a miner. It is recommended to follow the document and go to the faucet to apply for fil。 @DTanniks

**Comment by diwufeiwen** [comment]
./venus wallet balance t3uk4jewz7uwpgv5g4qj6xmkt4uaangnjt6gaawo2ao7lonjg4k47ublpuzl4cwdwrhyvyojwumpyzf6mggc5q
0 FIL
[root@nerpa_venus venus]# ./venus wallet balance t3s626pxg53xz6rv43dkuuv5xckbbxump3272vyvd6bcub2ybd5tmdlu3cwlyttqm64n62ifq7jumyrekwhopa
0 FIL

**Comment by diwufeiwen** [comment]
filecoinproject.slack.com -> fil-venus-cn   or fil-venus channel

**Comment by DTanniks** [comment]
I got the water from the tap and did I have the command to check the address balance with venus-wallet？
I have been able to check my balance：
```
./venus wallet balance t3s626pxg53xz6rv43dkuuv5xckbbxump3272vyvd6bcub2ybd5tmdlu3cwlyttqm64n62ifq7jumyrekwhopa
1000 FIL
```

**Comment by simlecode** [comment]
venus-wallet need to connected to the node to check the balance

**Comment by DTanniks** [comment]
I run：
```
nohup ./venus-sealer init \
--worker t3s626pxg53xz6rv43dkuuv5xckbbxump3272vyvd6bcub2ybd5tmdlu3cwlyttqm64n62ifq7jumyrekwhopa \
--owner t3uk4jewz7uwpgv5g4qj6xmkt4uaangnjt6gaawo2ao7lonjg4k47ublpuzl4cwdwrhyvyojwumpyzf6mggc5q  \
--sector-size 512M \
--network nerpa \
--node-url /ip4/127.0.0.1/tcp/3453 \
--messager-url /ip4/127.0.0.1/tcp/39812 \
--gateway-url /ip4/127.0.0.1/tcp/45132 \
--auth-token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoibWluZXIxIiwicGVybSI6ImFkbWluIiwiZXh0IjoiIn0.XegAOGgjVYsxdlHHf0L3XHEATlX3rvYFVknMT1Rz7AA \
--no-local-storage \
> sealer.log 2>&1 &
```
got：
```
2021-08-06T09:53:02.177+0800	ERROR	main	venus-sealer/init.go:295	Failed to initialize venus-miner: creating miner failed:
    main.storageMinerInit
        /root/venus/venus-sealer/app/venus-sealer/init.go:450
  - pushing createMiner message:
    main.createStorageMiner
        /root/venus/venus-sealer/app/venus-sealer/init.go:557
  - wallet(miner1) address t3uk4jewz7uwpgv5g4qj6xmkt4uaangnjt6gaawo2ao7lonjg4k47ublpuzl4cwdwrhyvyojwumpyzf6mggc5q not exists
2021-08-06T09:53:02.177+0800	INFO	main	venus-sealer/init.go:300	Cleaning up /root/.venussealer after attempt...
ERROR: Storage-miner init failed
```
`./venus-wallet ls`
```
t3s626pxg53xz6rv43dkuuv5xckbbxump3272vyvd6bcub2ybd5tmdlu3cwlyttqm64n62ifq7jumyrekwhopa
t3uk4jewz7uwpgv5g4qj6xmkt4uaangnjt6gaawo2ao7lonjg4k47ublpuzl4cwdwrhyvyojwumpyzf6mggc5q
```

**Comment by simlecode** [comment]
Please exec `./venus-gateway wallet list`, give me result

**Comment by DTanniks** [comment]
```
[
 	{
 		"Account": "miner1",
 		"SupportAccounts": [
 			"miner1"
 		],
 		"ConnectStates": [
 			{
 				"Addrs": [
 					"t3s626pxg53xz6rv43dkuuv5xckbbxump3272vyvd6bcub2ybd5tmdlu3cwlyttqm64n62ifq7jumyrekwhopa",
 					"t3uk4jewz7uwpgv5g4qj6xmkt4uaangnjt6gaawo2ao7lonjg4k47ublpuzl4cwdwrhyvyojwumpyzf6mggc5q"
 				],
 				"ChannelId": "abf374c6-87ba-434f-8a64-0a9ddc5b7b5e",
 				"Ip": "127.0.0.1:55296",
 				"RequestCount": 0,
 				"CreateTime": "2021-08-05T14:06:28.1327066+08:00"
 			}
 		]
 	}
 ]

```

**Comment by simlecode** [comment]
Please provide venus-messager config: `messager.toml`

**Comment by DTanniks** [comment]
> Please provide venus-messager config: `messager.toml`

```
  [api]
    Address = "/ip4/0.0.0.0/tcp/39812"
  
  [db]
    type = "mysql"
  
    [db.mysql]
      connMaxLifeTime = "1m0s"
      connectionString = "root:Root1234@(127.0.0.1:3306)/messager?parseTime=true&loc=Local"
      debug = false
      maxIdleConn = 10
      maxOpenConn = 10
  
    [db.sqlite]
      debug = false
      file = "./message.db"
  
  [gateway]
    remoteEnable = false
    token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoidGVzdG1pbmVyIiwicGVybSI6ImFkbWluIiwiZXh0IjoiIn0.oakIfSg1Iiv1T2F1BtH1bsb_1GeXWuirdPSjvE5wQLs"
    url = "/ip4/8.130.165.167/tcp/45132"
  
    [gateway.cfg]
      RequestQueueSize = 30
      RequestTimeout = "5m0s"
  
  [jwt]
    authURL = ""
  
    [jwt.local]
      secret = "d79e40006307e1d49cb90c5a654d34049069c7cc2b67c65b24f3da51bc9a9a10"
      token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoidmVudXMtbWVzc2FnZXItYWRtaW4iLCJwZXJtIjoiYWRtaW4iLCJleHQiOiIifQ.dsysX7aEYyIjTap0Uewqr28EGHxeEd9q-6nrcRTy_lE"
  
  [log]
    level = "info"
    path = "messager.log"
  
  [messageService]
    skipProcessHead = false
    skipPushMessage = false
    tipsetFilePath = "./tipset.json"
  
  [messageState]
    CleanupInterval = 86400
    DefaultExpiration = 259200
    backTime = 86400
  
  [node]
    token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoidGVzdG1pbmVyIiwicGVybSI6ImFkbWluIiwiZXh0IjoiIn0.oakIfSg1Iiv1T2F1BtH1bsb_1GeXWuirdPSjvE5wQLs"
    url = "/ip4/8.130.165.167/tcp/3453"
  
  [rateLimit]
    redis = ""
  
  [tracing]
    JaegerEndpoint = ""
    JaegerTracingEnabled = false
    ProbabilitySampler = 0.0
    ServerName = ""
  
  [wallet]
    scanInterval = 10
```

**Comment by simlecode** [comment]
oh, my god, you do not modify your configuration. please modify your configuration.

>   [db]
>     type = "mysql"
>   
>     [db.mysql]
>       connMaxLifeTime = "1m0s"
>       connectionString = "root:Root1234@(127.0.0.1:3306)/messager?parseTime=true&loc=Local" # Use your MySQL account and password
>       debug = false
>       maxIdleConn = 10
>       maxOpenConn = 10
>   
>     [db.sqlite]
>       debug = false
>       file = "./message.db"
>   
>   [gateway]
>     remoteEnable = false # change to true 
>     token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoidGVzdG1pbmVyIiwicGVybSI6ImFkbWluIiwiZXh0IjoiIn0.oakIfSg1Iiv1T2F1BtH1bsb_1GeXWuirdPSjvE5wQLs"
>     url = "/ip4/8.130.165.167/tcp/45132"  # change to /ip4/127.0.0.1/tcp/45132
>   

>   [jwt]
>     authURL = "" # change to auth url 

>   
>   [node]
>     token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoidGVzdG1pbmVyIiwicGVybSI6ImFkbWluIiwiZXh0IjoiIn0.oakIfSg1Iiv1T2F1BtH1bsb_1GeXWuirdPSjvE5wQLs"
>     url = "/ip4/8.130.165.167/tcp/3453"  # change to /ip4/127.0.0.1/tcp/3453

use `eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoibWluZXIxIiwicGVybSI6ImFkbWluIiwiZXh0IjoiIn0.XegAOGgjVYsxdlHHf0L3XHEATlX3rvYFVknMT1Rz7AA` instead of `eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoidGVzdG1pbmVyIiwicGVybSI6ImFkbWluIiwiZXh0IjoiIn0.oakIfSg1Iiv1T2F1BtH1bsb_1GeXWuirdPSjvE5wQLs`

**Comment by diwufeiwen** [comment]
nohup ./venus-messager run --auth-url=http://127.0.0.1:8989 --node-url=/ip4/127.0.0.1/tcp/3453 --gateway-url=/ip4/127.0.0.1/tcp/45132 --auth-token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoic2hhcmVkLXRrIiwicGVybSI6ImFkbWluIiwiZXh0IjoiIn0.mORFVknJmuWTUWRvDKsgw53CWbnfUIk74OgAa9bgU3E --db-type=sqlite > msg.log 2>&1 &

./venus-auth token list
num     name            perm            createTime              token
1       shared-tk       admin   2021-08-05 14:10:08     eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoic2hhcmVkLXRrIiwicGVybSI6ImFkbWluIiwiZXh0IjoiIn0.mORFVknJmuWTUWRvDKsgw53CWbnfUIk74OgAa9bgU3E
2       test            write   2021-08-05 14:10:33     eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoidGVzdCIsInBlcm0iOiJ3cml0ZSIsImV4dCI6IiJ9.aWoYo5MHxINSWqqV72Xzc7l1ZBc8UXkiMPIwn1NO2Fc

--auth-token ----》venus-auth管理着其他venus模块使用的jwt (opens new window)令牌，以便它们在网络上安全地相互通信。

为共享模块生成token。

# --perm specifies admin, sign, wirte or read permission of the token generated
$ ./venus-auth token gen --perm admin <SHARED>
<SHARED_ADMIN_AUTH_TOKEN>

**Comment by DTanniks** [comment]
> nohup ./venus-messager run --auth-url=http://127.0.0.1:8989 --node-url=/ip4/127.0.0.1/tcp/3453 --gateway-url=/ip4/127.0.0.1/tcp/45132 --auth-token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoic2hhcmVkLXRrIiwicGVybSI6ImFkbWluIiwiZXh0IjoiIn0.mORFVknJmuWTUWRvDKsgw53CWbnfUIk74OgAa9bgU3E --db-type=sqlite > msg.log 2>&1 &
> 
> ./venus-auth token list
> num name perm createTime token
> 1 shared-tk admin 2021-08-05 14:10:08 eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoic2hhcmVkLXRrIiwicGVybSI6ImFkbWluIiwiZXh0IjoiIn0.mORFVknJmuWTUWRvDKsgw53CWbnfUIk74OgAa9bgU3E
> 2 test write 2021-08-05 14:10:33 eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoidGVzdCIsInBlcm0iOiJ3cml0ZSIsImV4dCI6IiJ9.aWoYo5MHxINSWqqV72Xzc7l1ZBc8UXkiMPIwn1NO2Fc
> 
> --auth-token ----》venus-auth管理着其他venus模块使用的jwt (opens new window)令牌，以便它们在网络上安全地相互通信。
> 
> 为共享模块生成token。
> 
> # --perm specifies admin, sign, wirte or read permission of the token generated
> $ ./venus-auth token gen --perm admin
> <SHARED_ADMIN_AUTH_TOKEN>

Thank you for your answer.
` ./venus-sealer sectors pledge`
`./venus-sealer sectors list`
```
ID  State       OnChain  Active  Expiration  Deals  
1   PreCommit1  NO       NO      n/a         CC
```
But `tail -f sealer.log`
```
2021-08-06T11:12:30.664+0800	INFO	proof_event	proof_client/proof_event.go:39	restarting listenHeadChanges
2021-08-06T11:12:30.665+0800	ERROR	proof_event	proof_client/proof_event.go:28	listen head changes errored: listenHeadChanges ChainNotify call failed: address t02928 not exit
2021-08-06T11:12:31.666+0800	INFO	proof_event	proof_client/proof_event.go:39	restarting listenHeadChanges
2021-08-06T11:12:31.668+0800	ERROR	proof_event	proof_client/proof_event.go:28	listen head changes errored: listenHeadChanges ChainNotify call failed: address t02928 not exit
2021-08-06T11:12:32.669+0800	INFO	proof_event	proof_client/proof_event.go:39	restarting listenHeadChanges
2021-08-06T11:12:32.671+0800	ERROR	proof_event	proof_client/proof_event.go:28	listen head changes errored: listenHeadChanges ChainNotify call failed: address t02928 not exit
2021-08-06T11:12:33.671+0800	INFO	proof_event	proof_client/proof_event.go:39	restarting listenHeadChanges
2021-08-06T11:12:33.673+0800	ERROR	proof_event	proof_client/proof_event.go:28	listen head changes errored: listenHeadChanges ChainNotify call failed: address t02928 not exit
```
That's why？ @diwufeiwen

**Comment by diwufeiwen** [comment]
Did it run successfully? @DTanniks

**Comment by DTanniks** [comment]
> Did it run successfully? @DTanniks

Yes，thank you for your patient reply. I will close it immediately.

Also, do I need to reset the password every time I restart the Venus-wallet? It doesn't make sense to me.

**Comment by DTanniks** [comment]
Thinks. @diwufeiwen @simlecode

**Comment by xiaoyuaiheshui** [comment]
> https://venus.filecoin.io/guide/Using-venus -Shared-Modules.html，这个地址已经关闭了吗？

**Comment by zl03jsj** [comment]
> > https://venus.filecoin.io/guide/Using-venus -Shared-Modules.html，这个地址已经关闭了吗？

https://github.com/filecoin-project/venus-docs/blob/master/docs/guide/Using-venus-Shared-Modules.md
